set -g status-left-length 100
set -g status-right-length 100

set -g status-left "#[fg=#272e33,bg=#{?client_prefix,#e67e80,#a7c080},bold] #S #[default]"
set -g window-status-format         "#[fg=#859289,bg=#2e383c] #I #[default] #W "
set -g window-status-current-format "#[fg=#272e33,bg=#7fbbb3,bold] #I #[fg=#a7c080,bg=#374145] #W "
set -g window-status-separator ""

set -g status-right "#[fg=#859289]MercenarioZ  %a %d %b #[fg=#d3c6aa,bg=#374145] %H:%M "
