set -g status-left-length 100
set -g status-right-length 100

set -g status-left "#[fg=#2d353b,bg=#a7c080] #S "
set -g window-status-format         "#[fg=#d3c6aa,bg=#4f585e] #I #[fg=#9da9a0,bg=#343f44] #W "
set -g window-status-current-format "#[fg=#2d353b,bg=#7fbbb3] #I #[fg=#2d353b,bg=#dbbc7f] #W "
set -g window-status-separator ""

set -g status-right "#{?client_prefix,#[fg=#2d353b]#[bg=#e67e80] PREFIX ,} #[bg=#d699b6,fg=#2d353b] MercenarioZ #[fg=#2d353b,bg=#a7c080] %Y-%m-%d %H:%M "
