set -g status-left-length 100
set -g status-right-length 100

set -g status-left "#[fg=#1e1e2e,bg=#a6e3a1] #S "
set -g window-status-format         "#[fg=#cdd6f4,bg=#585b70] #I #[fg=#a6adc8,bg=#313244] #W "
set -g window-status-current-format "#[fg=#1e1e2e,bg=#89b4fa] #I #[fg=#1e1e2e,bg=#f9e2af] #W "
set -g window-status-separator ""

set -g status-right "#{?client_prefix,#[fg=#1e1e2e]#[bg=#f38ba8] PREFIX ,} #[bg=#e69cd4,fg=#1e1e2e] MercenarioZ #[fg=#1e1e2e,bg=#a6e3a1] %Y-%m-%d %H:%M "
