# everforest dark medium, same palette as nvim and ghostty
set -g status-style "fg=#d3c6aa,bg=#2d353b"

set -g message-style "fg=#d3c6aa,bg=#343f44,fill=#343f44,align=left"
set -g message-command-style "fg=#d3c6aa,bg=#343f44,fill=#343f44,align=left"
