background = #031219
adjust-cell-height = 10%
window-theme = dark
window-height = 40
window-width = 90
window-padding-x = 14
window-padding-y = 10
background-opacity = 0.7

selection-background = #2d3f76
selection-foreground = #c8d3f5

cursor-style = bar
cursor-style-blink = true
mouse-hide-while-typing = true

# keybindings
keybind = alt+s>r=reload_config
keybind = alt+s>x=close_surface

keybind = alt+s>n=new_window

# Native Quake-style terminal, available globally through the desktop portal.
keybind = global:super+shift+enter=toggle_quick_terminal

# tabs
keybind = alt+s>c=new_tab
keybind = alt+s>shift+l=next_tab
keybind = alt+s>shift+h=previous_tab
keybind = alt+s>comma=move_tab:-1
keybind = alt+s>period=move_tab:1

# quick tab switch
keybind = alt+s>1=goto_tab:1
keybind = alt+s>2=goto_tab:2
keybind = alt+s>3=goto_tab:3
keybind = alt+s>4=goto_tab:4
keybind = alt+s>5=goto_tab:5
keybind = alt+s>6=goto_tab:6
keybind = alt+s>7=goto_tab:7
keybind = alt+s>8=goto_tab:8
keybind = alt+s>9=goto_tab:9

# split
keybind = alt+s>\=new_split:right
keybind = alt+s>-=new_split:down

keybind = alt+s>j=goto_split:bottom
keybind = alt+s>k=goto_split:top
keybind = alt+s>h=goto_split:left
keybind = alt+s>l=goto_split:right

keybind = alt+s>z=toggle_split_zoom

keybind = alt+s>e=equalize_splits

# other
copy-on-select = false

font-size = 13.5
font-style = Medium


title = "GhosTTY"

wait-after-command = false
shell-integration = detect
window-save-state = always
gtk-single-instance = true
quit-after-last-window-closed = false
unfocused-split-opacity = 0.5
quick-terminal-position = center
quick-terminal-size = 65%,65%
shell-integration-features = cursor,sudo
