"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username$time$directory$git_branch$git_status$nodejs$golang$python
$character"""

[username]
format = "💩 [$user]($style) "
style_user = "bold green"
show_always = true

[hostname]
disabled = true

[time]
disabled = false
format = "󰥔 [$time]($style) "
style = "bold green"
time_format = "%H:%M:%S"

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[directory]
truncation_length = 2
style = "bold blue"

[git_branch]
symbol = " "
style = "bold purple"
format = "[$symbol$branch]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold red"
staged = "●"
modified = "M"
deleted = "✘"
untracked = "…"
stashed = "📦"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕"
conflicted = "⚔️"

[python]
pyenv_version_name = false
symbol = "🐍"
python_binary = ['python', 'python3']
format = '[$symbol $version]($style) '
detect_extensions = []
detect_files = []
detect_folders = []

[package]
disabled = true
