"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$git_branch\
$git_status\
$c\
$cpp\
$elixir\
$elm\
$gradle\
$haskell\
$julia\
$kotlin\
$nim\
$php\
$rust\
$scala\
$golang\
$java\
$nodejs\
$python\
$conda\
$docker_context\
$pixi\
$line_break\
$character
"""

[username]
disabled = false
show_always = false
style_user = "green"
style_root = "bold red"
format = '[$user]($style) '

[directory]
disabled = false
style = "bold cyan"
format = "[ $path]($style) "
truncation_length = 2
truncation_symbol = ".../"

[character]
format = '$symbol '
success_symbol = '[>](green)'
error_symbol = '[>](bold red)'
vimcmd_symbol = '[<](green)'
vimcmd_replace_one_symbol = '[<](purple)'
vimcmd_replace_symbol = '[<](purple)'
vimcmd_visual_symbol = '[<](yellow)'

[git_branch]
symbol = ""
style = "yellow"
format = '[$symbol $branch]($style) '

[git_status]
disabled = false
style = "yellow"
format = '([$all_status$ahead_behind]($style))'
conflicted = '=$count '
ahead = '↑$count '
behind = '↓$count '
diverged = '↑$ahead_count ↓$behind_count '
up_to_date = ''
untracked = '?$count '
stashed = '\$$count '
modified = '!$count '
staged = '+$count '
renamed = '»$count '
deleted = '✘$count '
typechanged = '~$count '

[conda]
symbol = " "
style = "green"
format = '[$symbol$environment]($style) '
ignore_base = false

[docker_context]
symbol = " "
style = "green"
format = '[$symbol$context]($style) '

[pixi]
symbol = "󰏗 "
style = "green"
format = '[$symbol($version)( $environment)]($style) '

[c]
symbol = " "
style = "purple"
format = '[$symbol($version)]($style) '

[cpp]
symbol = " "
style = "purple"
format = '[$symbol($version)]($style) '

[elixir]
symbol = " "
style = "purple"
format = '[$symbol($version)]($style) '

[elm]
symbol = " "
style = "purple"
format = '[$symbol($version)]($style) '

[golang]
symbol = " "
style = "purple"
format = '[$symbol($version)]($style) '

[gradle]
symbol = " "
style = "purple"
format = '[$symbol($version)]($style) '

[haskell]
symbol = " "
style = "purple"
format = '[$symbol($version)]($style) '

[java]
symbol = " "
style = "purple"
format = '[$symbol($version)]($style) '

[julia]
symbol = " "
style = "purple"
format = '[$symbol($version)]($style) '

[kotlin]
symbol = " "
style = "purple"
format = '[$symbol($version)]($style) '

[nodejs]
symbol = " "
style = "purple"
format = '[$symbol($version)]($style) '
detect_files = ["package.json"]
detect_extensions = ["js", "ts"]
detect_folders = ["node_modules"]

[nim]
symbol = "󰆥 "
style = "purple"
format = '[$symbol($version)]($style) '

[php]
symbol = " "
style = "purple"
format = '[$symbol($version)]($style) '

[python]
symbol = " "
style = "purple"
format = '[$symbol($version)( $virtualenv)]($style) '

[rust]
symbol = "󱘗 "
style = "purple"
format = '[$symbol($version)]($style) '

[scala]
symbol = " "
style = "purple"
format = '[$symbol($version)]($style) '
